-- Gui to Lua
-- Version: 3.2

-- Instances:

local ToggleGui = Instance.new("ScreenGui")
local Toggle = Instance.new("ImageButton")
local UICorner = Instance.new("UICorner")

--Properties:

ToggleGui.Name = "ToggleGui"
ToggleGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
ToggleGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

Toggle.Name = "Toggle"
Toggle.Parent = ToggleGui
Toggle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Toggle.BorderColor3 = Color3.fromRGB(0, 0, 0)
Toggle.BorderSizePixel = 0
Toggle.Position = UDim2.new(0.418194324, 0, 0.0718582869, 0)
Toggle.Size = UDim2.new(0, 100, 0, 100)
Toggle.Image = "http://www.roblox.com/asset/?id=16541142603"

UICorner.Parent = Toggle

-- Scripts:

local function FZIJBCI_fake_script() -- Toggle.changer 
	local script = Instance.new('Script', Toggle)

	
	while true do
	script.Parent.ImageColor3 = Color3.new(1,0,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.2,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.3,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.4,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.5,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.6,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.7,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.8,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0.9,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.9,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.8,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.7,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.6,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.5,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.4,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.3,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.2,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.1,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.2)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.3)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.4)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.5)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.6)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.7)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.8)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,0.9)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,1,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.9,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.8,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.7,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.6,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.5,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.4,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.3,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.2,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0.1,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.1,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.2,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.3,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.4,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.5,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.6,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.7,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.8,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(0.9,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,1)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.9)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.8)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.7)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.6)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.5)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.4)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.3)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.2)
	wait(0.01)
	script.Parent.ImageColor3 = Color3.new(1,0,0.1)
	wait(0.01)
	end
	
end
coroutine.wrap(FZIJBCI_fake_script)()
local function KVPCY_fake_script() -- Toggle.Dragify 
	local script = Instance.new('LocalScript', Toggle)

	local UIS = game:GetService("UserInputService")
	function dragify(Frame)
		dragToggle = nil
		dragSpeed = 0
		dragInput = nil
		dragStart = nil
		dragPos = nil
		function updateInput(input)
			Delta = input.Position - dragStart
			Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + Delta.X, startPos.Y.Scale, startPos.Y.Offset + Delta.Y)
			game:GetService("TweenService"):Create(Frame, TweenInfo.new(0.15), {Position = Position}):Play()
		end
		Frame.InputBegan:Connect(function(input)
			if (input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch) and UIS:GetFocusedTextBox() == nil then
				dragToggle = true
				dragStart = input.Position
				startPos = Frame.Position
				input.Changed:Connect(function()
					if input.UserInputState == Enum.UserInputState.End then
						dragToggle = false
					end
				end)
			end
		end)
		Frame.InputChanged:Connect(function(input)
			if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
				dragInput = input
			end
		end)
		game:GetService("UserInputService").InputChanged:Connect(function(input)
			if input == dragInput and dragToggle then
				updateInput(input)
			end
		end)
	end
	dragify(script.Parent)
	
end
coroutine.wrap(KVPCY_fake_script)()
local function BDKKFW_fake_script() -- Toggle.LocalScript 
	local script = Instance.new('LocalScript', Toggle)

	local ExecHub = game.Players.LocalPlayer.PlayerGui.ExecHub
	local Fram = ExecHub.Fram
	local prent = script.Parent
	prent.MouseButton1Click:Connect(function() 
		Fram.Visible = not Fram.Visible
	end)
	
end
coroutine.wrap(BDKKFW_fake_script)()
